namespace: jitstrategies
name: chainflip
version: 1.0.0
readme: README.md
authors:
  - JIT Strategies DevOps <devops@jitstrategies.com>
description: A collection of roles to deploy and manage Chainflip nodes.
license:
  - Apache-2.0
tags:
  - blockchain
  - dex
dependencies:
  community.general: ">=6.1.0"
repository: https://github.com/jit-strategies/ansible-chainflip
documentation: https://docs.chainflip.io
homepage: https://jitstrategies.com
issues: https://github.com/jit-strategies/ansible-chainflip/issues
build_ignore:
  - .ansible-lint
  - .github
  - .gitignore
  - requirements.txt
