---
chainflip_chain: berghain
chainflip_release: "{{ chainflip_chain }}"
chainflip_apt_repository_url: https://pkgs.chainflip.io
chainflip_apt_repository_key_id: 4E506212E4EF4E0D3E37E568596FBDCACBBCDD37
health_check: true
only_configure: false
config_path: "/etc/chainflip"
generate_keys_from_seed: false
save_keys_json: false
save_keys_json_file: "{{ config_path }}/keys/keys.json"

node_chaindata_path: "{{ config_path }}/chaindata"
node_chainspec_file: "{{ config_path }}/{{ chainflip_chain }}.chainspec.json"
node_p2p_key_file: "{{ config_path }}/keys/node_key_file"
node_systemd_override: true
node_disable_mdns: false
node_sync_mode: "full" # full, fast, fast-unsafe, warp
node_dev_mode: false
node_validator: true
node_archive: false
node_prometheus_external: false
node_state_cache_size: 0
node_use_journal: false
node_bootnodes: ""
node_rpc_cors: ""
node_rpc_port: 9944
node_extra_args: ""
# node_in_peers: 200
# node_out_peers: 200

engine_enabled: true
engine_version: "1.0"
engine_generate_eth_key: false
engine_systemd_override: true
engine_debug: false
engine_debug_target: "chainflip_engine=debug"
engine_use_journal: false
engine_config_file: "{{ config_path }}/config/Settings.toml"
# [node_p2p]
engine_p2p_key_file: "{{ node_p2p_key_file }}"
engine_node_p2p_port: 8078
# [state_chain]
engine_state_chain_ws_endpoint: "ws://127.0.0.1:9944"
engine_state_chain_signing_key_file: "{{ config_path }}/keys/signing_key_file"
engine_state_chain_ss58_address_file: "{{ config_path }}/keys/ss58_address_file"
# [signing]
engine_signing_db_file: "{{ config_path }}/data.db"
# [eth]
engine_eth_private_key_file: "{{ config_path }}/keys/ethereum_key_file"
engine_eth_address_file: "{{ config_path }}/keys/ethereum_address"
# [eth.rpc]
engine_eth_rpc_ws_endpoint: "ws://127.0.0.1:8080"
engine_eth_rpc_http_endpoint: "http://127.0.0.1:8080"
# [eth.backup_rpc]
engine_eth_backup_rpc_ws_endpoint: ""
engine_eth_backup_rpc_http_endpoint: ""
# [dot.rpc]
engine_dot_rpc_ws_endpoint: "ws://127.0.0.1:8081"
engine_dot_rpc_http_endpoint: "http://127.0.0.1:8081"
# [dot.backup_rpc]
engine_dot_backup_rpc_ws_endpoint: ""
engine_dot_backup_rpc_http_endpoint: ""
# [btc.rpc]
engine_btc_rpc_http_endpoint: "http://127.0.0.1:8082"
engine_btc_rpc_basic_auth_user: "flip"
engine_btc_rpc_basic_auth_password: "flip"
# [btc.backup_rpc]
engine_btc_backup_rpc_http_endpoint: ""
engine_btc_backup_rpc_basic_auth_user: ""
engine_btc_rpc_backup_basic_auth_bassword: ""
# [health_check]
engine_health_check_hostname: "127.0.0.1"
engine_health_check_port: "5555"
# [prometheus]
engine_prometheus_hostname: "127.0.0.1"
engine_prometheus_port: 5566
