---
- name: Converge
  hosts: all
  tasks:
    - name: "Include node"
      ansible.builtin.include_role:
        name: node
      vars:
        node_archive: true
        engine_generate_eth_key: true
        chainflip_chain: perseverance
