---

dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: validator01
    image: docker.io/geerlingguy/docker-ubuntu2204-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    pre_build_image: true
provisioner:
  name: ansible
  # log: false
  env:
    ANSIBLE_ROLES_PATH: "../../roles"

verifier:
  name: ansible
