---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Run CLI binary
      ansible.builtin.command:
        cmd: chainflip-cli --help

    - name: Run node binary
      ansible.builtin.command:
        cmd: chainflip-node -V
