---
- name: Force daemon config reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart chainflip-engine
  ansible.builtin.systemd:
    name: chainflip-engine{{ engine_version }}
    daemon_reload: true
    state: restarted

- name: Restart chainflip-node
  ansible.builtin.systemd:
    name: chainflip-node
    daemon_reload: true
    state: restarted

- name: Journal restart
  ansible.builtin.systemd:
    name: systemd-journald
    state: restarted
