---
- name: Daemon reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart chainflip-engine
  ansible.builtin.systemd:
    name: chainflip-engine
    state: restarted

- name: Restart chainflip-node
  ansible.builtin.systemd:
    name: chainflip-node
    state: restarted
