---
galaxy_info:
  role_name: cli
  author: JIT Strategies DevOps <devops@jitstrategies.com>
  description: Role for running CLI commands on a Chainflip Node node
  company: JIT Strategies
  license: Apache-2.0
  min_ansible_version: "2.4"
  platforms:
    - name: Ubuntu
      versions:
        - focal
  galaxy_tags:
    - chainflip
    - dex
    - p2p
dependencies: []
