- name: Node Healthcheck
  retries: 5
  delay: 3
  register: node_result
  until: node_result.status == 200
  ansible.builtin.uri:
    url: "http://localhost:{{ node_rpc_port }}"
    body:
      id: 1
      jsonrpc: "2.0"
      method: system_health
    method: POST
    body_format: json

# Disabled until fixed upstream
# - name: Engine Healthcheck
#   retries: 5
#   delay: 3
#   register: engine_result
#   until: engine_result.status == 200
#   ansible.builtin.uri:
#     url: "http://{{ engine_health_check_hostname }}:{{ engine_health_check_port }}/health"
