- name: Print the SS58 address
  ansible.builtin.debug:
    msg: "Node engine configured with SS58 address: {{ generated_ss58Address }}"
  when:
    - create_signing_key_file.changed

- name: Print the Ethereum address
  ansible.builtin.debug:
    msg: "Node engine configured with Ethereum address: 0x{{ (validator_keys.stdout | from_json).ethereum_address }}"
  when:
    - create_ethereum_key_file.changed
