- name: Generate keys with cli
  no_log: true
  register: validator_keys
  ansible.builtin.command:
    cmd: chainflip-cli generate-keys --json
  changed_when: false
  when:
    - not generate_keys_from_seed

- name: Generate keys from seed phrase
  when: generate_keys_from_seed
  block:
    - name: Seed phrase prompt
      ansible.builtin.pause:
        prompt: "Enter the 12-word seed phrase:"
        echo: false
      no_log: true
      register: seed_phrase_prompt

    - name: Generate new keys with provided seed phrase
      no_log: true
      register: validator_keys_from_seed
      ansible.builtin.command:
        cmd: chainflip-cli generate-keys --json --seed-phrase "{{ seed_phrase_prompt.user_input }}"
      changed_when: false

    - name: Save keys from seed
      ansible.builtin.set_fact:
        validator_keys: "{{ validator_keys_from_seed }}"
      no_log: true

- name: Save generated address as fact
  ansible.builtin.set_fact:
    generated_ss58Address: "{{ (validator_keys.stdout | from_json).signing_account_id }}"
  changed_when: false
