---
- name: Provision validator
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Deploy Chainflip node
      ansible.builtin.include_role:
        name: jitstrategies.chainflip.node
      vars:
        node_archive: true
