---
- name: Run command {{ command }}
  ansible.builtin.shell:
    cmd: >
      echo "y" | chainflip-cli --config-root "{{ config_root }}" {{ command }}
  register: result
  until: result.rc == 0
  delay: "{{ delay }}"
  retries: "{{ retries }}"
